name: Chrome Stable

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the chrome-stable image
      run: docker build --build-arg "USE_CHROME_STABLE=true" -t my4052/chrome:stable .

    - name: Test the chrome-stable image
      run: docker run --ipc=host -e CI=true --entrypoint ./test.sh my4052/chrome:stable
