name: Chromium Stable

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the latest image
      run: docker build -t my4052/chrome:latest .

    - name: Test the latest image
      run: docker run --ipc=host -e CI=true --entrypoint ./test.sh my4052/chrome:latest
